sudo: false
language: java

script:
  - gradle build
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ecse429-fall2018 -Dsonar.login=${superSecretToken} -Dsonar.projectKey=ecse429-tutorial-05-Gabetn -Dsonar.projectName=ecse429-tutorial-05-Gabetn

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

